import { createApp } from 'vue'
import App from './Sociedad.vue' 
//import App from './EgresadosAdmi.vue'
//import App from './principal.vue'
//import App from './principalAdmi.vue'
//import App from './Nosotros.vue'
//import App from './Pregrado.vue'
//import App from './Nosotrosadmin.vue'
//import App from './principalAdmi.vue'
//import App from './investigaciones.vue'
//import App from './actividades_noticias.vue'
createApp(App).mount('#app')